foodtasker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foodtaskerapp.urls')),

     # Sign In/ Sign Up/ Sign Out
    path('api/social/', include('rest_framework_social_oauth2.urls')),
    #path('api/auth/', include('django.contrib.auth.urls', namespace='auth')),
    # /convert-token (sign in/ sign up)
    # /revoke-token (sign out)
]

foodtaskerapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', views.home, name='home'),
	    path('restaurant/sign-in/', auth_views.LoginView.as_view(template_name='foodtaskerapp/restaurant/sign_in.html'),
	  	name='restaurant-sign-in'),
    path('restaurant/sign-out/', auth_views.LogoutView.as_view(next_page='/'),
	  	name='restaurant-sign-out'),
    path('restaurant/', views.restaurant_home, name='restaurant-home'),
    path('restaurant/sign-up/', views.restaurant_sign_up, name='restaurant-sign-up'),
    path('restaurant/account/', views.restaurant_account, name='restaurant-account'),
    path('restaurant/meal/', views.restaurant_meal, name='restaurant-meal'),
    path('restaurant/order/', views.restaurant_order, name='restaurant-order'),
    path('restaurant/report/', views.restaurant_report, name='restaurant-report'),

    path('restaurant/meal/add/', views.restaurant_add_meal, name='restaurant-add-meal'),
    path('restaurant/meal/edit/<meal_id>/', views.restaurant_edit_meal, name='restaurant-edit-meal'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodtaskerapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



class Restaurant(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='restaurant')
	name = models.CharField(max_length=500)
	phone = models.CharField(max_length=15)
	address = models.CharField(max_length=125)
	logo = models.ImageField(upload_to='restaurant_logo/', blank=False)

	def __str__(self):
		return self.name

class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="customer")
	avatar = models.CharField(max_length=500)
	phone = models.CharField(max_length=15, blank=True)
	address = models.CharField(max_length=125, blank=True)

	def __str__(self):
		return self.user.get_full_name()

class Driver(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="driver")
	avatar = models.CharField(max_length=500)
	phone = models.CharField(max_length=15, blank=True)
	address = models.CharField(max_length=125, blank=True)

	def __str__(self):
		return self.user.get_full_name()

class Meal(models.Model):
	restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
	name = models.CharField(max_length=500)
	short_description = models.CharField(max_length=500)
	image = models.ImageField(upload_to='meal_images/', blank=False)
	price = models.IntegerField(default=0)

	def __str__(self):
		return self.name

class Order(models.Model):
	COOKING = 1
	READY = 2
	ONTHEWAY = 3
	DELIVERED = 4

	STATUS_CHOICE = (
		(COOKING, "Cooking"),
		(READY, "Ready"),
		(ONTHEWAY, "On the way"),
		(DELIVERED, "Delivered"),
		)

	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
	driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
	address = models.CharField(max_length=500)
	total = models.IntegerField()
	status = models.IntegerField(choices = STATUS_CHOICE)
	created_at = models.DateTimeField(default= timezone.now)
	picked_at = models.DateTimeField(blank = True, null = True)

	def __str__(self):
		return str(self.id)

class OrderDetails(models.Model):
	order = models.ForeignKey(Order,on_delete=models.CASCADE, related_name='order_details')
	meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	sub_total = models.IntegerField()

	def __str__(self):
		return str(self.id)

foodtaskerapp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Restaurant, Meal

class UserForm(forms.ModelForm):
	email = forms.CharField(max_length=100, required=True)
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ("username", "password", "first_name", "last_name", "email")


class UserFormEdit(forms.ModelForm):
	email = forms.CharField(max_length=100, required=True)
	class Meta:
		model = User
		fields = ("first_name", "last_name", "email")

class RestaurantForm(forms.ModelForm):
	class Meta:
		model = Restaurant
		fields = ("name", "phone", "address", "logo")

class MealForm(forms.ModelForm):
	class Meta:
		model = Meal
		exclude = ("restaurant",)

foodtaskerapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User


from .models import Meal, Order
from .forms import UserForm, RestaurantForm , UserFormEdit, MealForm

def home(request):
	return redirect(restaurant_home)

@login_required(login_url='/restaurant/sign-in/')
def restaurant_home(request):
	# return render(request, 'foodtaskerapp/restaurant/home.html', {})
	return redirect(restaurant_order)


@login_required(login_url='/restaurant/sign-in/')
def restaurant_account(request):
	user_form_edit = UserFormEdit(instance = request.user)
	restaurant_form_edit = RestaurantForm(instance = request.user.restaurant)

	if request.method == "POST":
		user_form_edit = UserFormEdit(request.POST, instance=request.user)
		restaurant_form_edit = RestaurantForm(request.POST, request.FILES, instance = request.user.restaurant)

		if user_form_edit.is_valid() and restaurant_form_edit.is_valid():
			user_form_edit.save()
			restaurant_form_edit.save()

	return render(request, 'foodtaskerapp/restaurant/account.html', {
		"user_form_edit": user_form_edit,
		"restaurant_form_edit": restaurant_form_edit
		})

@login_required(login_url='/restaurant/sign-in/')
def restaurant_meal(request):
	meals = Meal.objects.filter(restaurant = request.user.restaurant).order_by("-id")
	return render(request, 'foodtaskerapp/restaurant/meal.html', {
		"meals": meals
		})

@login_required(login_url='/restaurant/sign-in/')
def restaurant_add_meal(request):
	form = MealForm()

	if request.method == "POST":
		form = MealForm(request.POST, request.FILES)

		if form.is_valid():
			meal = form.save(commit=False)
			meal.restaurant = request.user.restaurant
			meal.save()
			return redirect(restaurant_meal)

	return render(request, 'foodtaskerapp/restaurant/add_meal.html', {
		"form": form,
		})

@login_required(login_url='/restaurant/sign-in/')
def restaurant_edit_meal(request, meal_id):
	form = MealForm(instance = Meal.objects.get(id = meal_id ))

	if request.method == "POST":
		form = MealForm(request.POST, request.FILES, instance = Meal.objects.get(id = meal_id ))

		if form.is_valid():
			form.save()
			return redirect(restaurant_meal)

	return render(request, 'foodtaskerapp/restaurant/edit_meal.html', {
		"form": form,
		})



@login_required(login_url='/restaurant/sign-in/')
def restaurant_order(request):
	if request.method == "POST":
		order = Order.objects.get(id = request.POST["id"], restaurant = request.user.restaurant)
		
		if order.status == Order.COOKING:
			order.status = Order.READY
			order.save()

	orders = Order.objects.filter(restaurant = request.user.restaurant).order_by("-id")
	return render(request, 'foodtaskerapp/restaurant/order.html', {"orders": orders })

@login_required(login_url='/restaurant/sign-in/')
def restaurant_report(request):
	return render(request, 'foodtaskerapp/restaurant/report.html', {})

def restaurant_sign_up(request):
	user_form = UserForm()
	restaurant_form = RestaurantForm()

	if request.method == "POST":
		user_form = UserForm(request.POST)
		restaurant_form = RestaurantForm(request.POST, request.FILES)

		if user_form.is_valid() and restaurant_form.is_valid():
			new_user = User.objects.create_user(**user_form.cleaned_data)
			new_restaurant = restaurant_form.save(commit=False) # create restaurant object in memory without saving to db
			new_restaurant.user = new_user
			new_restaurant.save() # now save to database

			# sign in the just created user
			login(request, authenticate(
				username = user_form.cleaned_data["username"],
				password = user_form.cleaned_data["password"]
				))

			return redirect(restaurant_home) # redirect to the home page after authenticating user

	return render(request, 'foodtaskerapp/restaurant/sign_up.html', {
		"user_form": user_form,
		"restaurant_form": restaurant_form
		})

foodtaskerapp/templates/foodtaskerapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title%} {% endblock%}</title>
	<link rel="stylesheet" href="{% static 'foodtaskerapp/css/materialize.min.css' %}">
	<script src="{% static 'foodtaskerapp/js/materialize.min.js' %}"></script>
	<link rel="stylesheet" href="{% static 'foodtaskerapp/css/style.css' %}">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col s12 s9 s6 s3">
				<br/>
				<br/>
					{% block sidebar%} {% endblock%}
					{% block content%} {% endblock %}
			</div>
		</div>
	</div>
	
</body>
</html>

foodtaskerapp/templates/foodtaskerapp/base_signup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title%} {% endblock%}</title>
	<link rel="stylesheet" href="{% static 'foodtaskerapp/css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'foodtaskerapp/css/style.css' %}">
	<script src="{% static 'foodtaskerapp/js/materialize.min.js' %}"></script>
</head>
<body class="bg-blue">

	<div class="container">
		<div class="row">
			<div class="col l12 m9 s9">
				<br/>
				<br/>
				<div class="">
					<div class="">
						{% block content %} 
						{% endblock %}
					</div>
				</div>
			</div>
		</div>
	</div>

	
</body>
</html>

foodtaskerapp/templates/foodtaskerapp/restaurant/account.html
{% extends 'foodtaskerapp/restaurant/base.html' %}
{% load materializecss %}
{% block title %} Restaurant | Account {% endblock title %}

{% block content %}
	<div class="main s8 m4">
		<div class="card"> <!-- card -->
			<div class="bg-blue"> <!-- card-title -->
				<h4 class="center"> Account </h4>
			</div>
			<div class=""> <!-- card-content -->
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ user_form_edit|materializecss }}
					{{ restaurant_form_edit|materializecss }}
					<button type="submit" class="btn btn-pink right">Update</button>
				</form>
			</div>
		</div>
	</div>
{% endblock content%}

foodtaskerapp/templates/foodtaskerapp/restaurant/add_meal.html
{% extends 'foodtaskerapp/restaurant/base.html' %}
{% load materializecss %}
{% block title %} Restaurant | Account {% endblock title %}

{% block content %}
	<div class="main s8 m4">
		<div class="card"> <!-- card -->
			<div class="bg-blue"> <!-- card-title -->
				<h4 class="center"> Add Meal </h4>
			</div>
			<div class=""> <!-- card-content -->
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form|materializecss }}
				
					<button type="submit" class="btn btn-pink right">Add</button>
				</form>
			</div>
		</div>
	</div>
{% endblock content%}

foodtaskerapp/templates/foodtaskerapp/restaurant/base.html
{% extends 'foodtaskerapp/base.html' %}
{% block title %} Restaurant Page {% endblock title %}

{% block sidebar %}
<!-- tutor's sidebar -->


{% url 'restaurant-order' as restaurant_order_url %}
{% url 'restaurant-account' as restaurant_account_url %}
{% url 'restaurant-report' as restaurant_report_url %}
{% url 'restaurant-meal' as restaurant_meal_url %}


<div class="sidebar">
	<div class="center">
		<img class="circle" src="{{ MEDIA_URL }}{{ user.restaurant.logo }}"
		width="70" height="70" />
		<br/>
		<h4>Hi, {{ user.get_full_name }}</h4>
		<h5>{{ user.restaurant.name }}</h5>
	</div>

	<div class="list-group">
		<span class="text-uppercase">Dashboard</span>

		<a href="{% url 'restaurant-order' %}" class="list-group-item {% if request.path == restaurant_order_url %} active {% endif %}">Orders</a>
		<a href="{% url 'restaurant-meal' %}" class="list-group-item {% if request.path == restaurant_meal_url %} active {% endif %}">Meals</a>
		<a href="{% url 'restaurant-report' %}" class="list-group-item {% if request.path == restaurant_report_url %} active {% endif %}">Reports</a>

		<span class="text-uppercase">Profile</span>
		<a href="{% url 'restaurant-account' %}" class="list-group-item {% if request.path == restaurant_account_url %} active {% endif %}">Account</a>
	</div>

	<div class="text-center">
		<a href="{% url 'restaurant-sign-out' %}?next={{ request.path }}"
		class="btn btn-pink">Logout</a>
	</div>
</div>


<!-- My customized sidebar -->
<!-- <div class="sidenavi">
	<div class="center group">
		<img src="{{ MEDIA_URL }}{{ request.user.restaurant.logo }}" alt="Restaurant Logo" class="circle" width="70" height="70">
		<h4>Hi, {{user.get_full_name}}</h4>
		<h5>{{user.restaurant.name }}</h5>
	</div>
	<hr/>
	<br/>


	<div class="group">
		<span class="text-uppercase">Dashboard</span>
		<a href="{% url 'restaurant-order' %}">Orders</a>
		<a href="{% url 'restaurant-meal' %}" >Meals</a>
		<a href="{% url 'restaurant-report' %}">Reports</a>

		<span class="text-uppercase">Profile</span>
		<a href="{% url 'restaurant-account' %}">Account</a>

	</div>
	<div class="center">
		<a href="{% url 'restaurant-sign-out' %}?next={{ request.path }}"
		class="btn btn-pink">Logout</a>
	</div>

</div> -->


{% endblock sidebar %}

foodtaskerapp/templates/foodtaskerapp/restaurant/edit_meal.html
{% extends 'foodtaskerapp/restaurant/base.html' %}
{% load materializecss %}
{% block title %} Restaurant | Account {% endblock title %}

{% block content %}
	<div class="main s8 m4">
		<div class="card"> <!-- card -->
			<div class="bg-blue"> <!-- card-title -->
				<h4 class="center"> Edit Meal </h4>
			</div>
			<div class=""> <!-- card-content -->
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form|materializecss }}
				
					<button type="submit" class="btn btn-pink right">Update</button>
				</form>
			</div>
		</div>
	</div>
{% endblock content%}

foodtaskerapp/templates/foodtaskerapp/restaurant/meal.html
{% extends 'foodtaskerapp/restaurant/base.html' %}
{% block title %} Restaurant | Meal {% endblock title %}

{% block content%}
	<div class="main">
		<div class="card">
			<div class="card-title bg-blue">
				<h4 class="center"> Meals </h4>
			</div>
			<div class="card-content">
				<div class="right">
					<a href="{% url 'restaurant-add-meal' %}" class="btn btn-pink">Add Meal</a>
					<br/>
					<br/>
				</div>
				<table class="table striped highlight responsive-table">
					<thead>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th>Short Description</th>
							<th>Price</th>
							<th class="center">Image</th>
						</tr>
					</thead>

					<tbody>
						{% for meal in meals %}
							<tr>
								<td scope="row">{{meal.id}}</td>
								<td><a href="{% url 'restaurant-edit-meal' meal.id %}">{{ meal.name }}</a></td>
								<td>{{ meal.short_description }}</td>
								<td>{{ meal.price }}</td>
								<td class="center"><img src="{{ MEDIA_URL }}{{ meal.image }}" alt="" class="img circle" width="50" height="50"></td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	
{% endblock content%}

foodtaskerapp/templates/foodtaskerapp/restaurant/order.html
{% extends 'foodtaskerapp/restaurant/base.html' %}
{% block title %} Restaurant | Order {% endblock title %}

{% block content%}
<div class="main">
	<div class="card">
		<div class="card-title bg-blue">
			<h4 class="center"> Orders </h4>
		</div>
		<div class="card-content">
			<br/>
			<table class="table striped highlight responsive-table">
				<thead>
					<tr>
						<th>ID</th>
						<th>Order Details</th>
						<th>Customer </th>
						<th>Driver</th>
						<th>Total</th>
						<th>Status</th>
						<th>Action</th>

					</tr>
				</thead>

				<tbody>
					{% for order in orders %}
					<tr>
						<td scope="row">{{ order.id }}</td>
						<td>
							{% for od in order.order_details.all %}
								{{ od.meal.name }} {{ od.meal.price }} 
								x {{ od.quantity }} = ${{ od.sub_total }}
							{% endfor %}
						</td>
						<td>{{order.customer}}</td>
						<td>{{order.driver}}</td>
						<td>{{order.total}}</td>
						<td>{{order.get_status_display}}</td>
						<td>
							{% if order.status == 1%}
								<form method="POST">
									{% csrf_token %}
									<input name="id" value="{{ order.id }}" hidden>
									<button class="btn green accent-3">Ready</button>
								</form>
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock content%}

foodtaskerapp/templates/foodtaskerapp/restaurant/report.html
{% extends 'foodtaskerapp/restaurant/base.html' %}
{% block title %} Restaurant | Report {% endblock title %}

{% block content%}
	<div class="main">
		<h1>Restaurant - Report</h1>
	</div>
{% endblock content%}

foodtaskerapp/templates/foodtaskerapp/restaurant/sign_in.html
{% extends "foodtaskerapp/base_signup.html" %}
{% load materializecss %}
{% block title %} Sign in {% endblock title%}

{% block content %}

	<h3>Sign in page</h3>
	<form method="POST">
		{% csrf_token %}
		{{ form|materializecss }}
		<button type="submit" class="btn btn-pink right"> Sign In</button>
	</form>
	<a href="{% url 'restaurant-sign-up' %}">Become a Restaurant  </a>
	<!-- <a href="{% url 'social:begin' 'facebook' %}?next={{restaurant}}" class="btn blue accent-3">Login in Facebook</a> -->
{% endblock content %}

foodtaskerapp/templates/foodtaskerapp/restaurant/sign_up.html
{% extends "foodtaskerapp/base_signup.html" %}
{% load materializecss %}
{% block title %} Sign Up {%endblock title%}

{% block content %}
	<h3>Sign up page</h3>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<h4>Owner Info</h4>
		{{ user_form|materializecss }}
		<h4>Restaurant Info</h4>
		{{ restaurant_form|materializecss }}
		<button type="submit" class="btn btn-pink right"> Sign Up</button>
	</form>
	<a href="{% url 'restaurant-sign-in' %}">Already have an account? Sign In</a>
	<!-- <a href="{% url 'social:begin' 'facebook' %}?next={{restaurant}}" class="btn blue accent-3">Sign Up Facebook</a> -->
{% endblock content %}